### ISSUE TITLE
[enhancement]: minor changes to meta data to improve Unified Task Inbox integration 

### ISSUE THREAD

**Issue by rallen2010** [flowsforapex/apex-flowsforapex#523]
### Feature description

A set of minor changes to meta data and views to better support integration of Flow for APEX tasks into the APEX Unified Task Inbox:

- [x] Add created_by to flow_processes
- [x] Expose task became_current 
- [x] create new view specifically for Unified Task Inbox integration

**Comment by rallen2010** [comment]
This needs more work in next release to add better support for task priorities, due dates, etc.
